### ISSUE TITLE
Hosting on firebase with ci/cd

### ISSUE THREAD

**Issue by faddalibrahim** [gdscashesi/ashesi-hacker-league-frontend#14]
Setup firebase hosting with URL (https://ashesi-hacker-leage.....)

And ci/cd with development branch

**Comment by DaveSaah** [comment]
I have created a firebase project for it. Send your gmails via the discord channel so I could add everyone.

**Comment by DaveSaah** [comment]
Cannot setup github actions. No permission. There are still issues with package versions. I can't really do anything.

**Comment by faddalibrahim** [comment]
@DaveSaah I already assigned you a task. Check the project board

i will handle the firebase hosting, using the gdsc's email
