### ISSUE TITLE
Uppercased Folder Names

### ISSUE THREAD

**Issue by Oheneba-Dade** [gdscashesi/ashesi-hacker-league-frontend#29]
Some folder names are uppercased which may not be conventional

**Comment by faddalibrahim** [comment]
indicate which parts

on my end, i can see all folders in lowercase

**Comment by Oheneba-Dade** [comment]
oh okay. when I viewed the development branch the pages have uppercased folder names. (Home, Table, Login)

**Comment by faddalibrahim** [comment]
pull from development again and let's see

**Comment by Oheneba-Dade** [comment]
yeah I just did and its no longer the case. I'm closing the issue then
